version: "3.8"

services:
  personalwebsite:
    container_name: personalwebsite
    image: personalwebsite
    build:
      context: .
    ports:
      - 3000:3000
    deploy:
      restart_policy:
        condition: unless-stopped