server {
    listen 80;
    server_name sbirka;

    server_tokens off;

    root /usr/share/nginx/html;
    index index.html;

    ssi on;
    ssi_types text/shtml text/html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'strict-dynamic' 'sha256-0GkazRTE8onURxCn+8SpdrFT1z4HKpFZsivrD7luYIo=' 'unsafe-inline' https: http:; style-src 'self'; img-src 'self'; base-uri 'none'; require-trusted-types-for 'script';";
}