server {
    listen 80;
    listen [::]:80;

    server_name davidweis.eu www.davidweis.eu;
        
    location / {
        proxy_pass http://personalwebsite:3000/;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name davidweis.eu www.davidweis.eu;

    ssl_certificate /path/to/fullchain.pem;
    ssl_certificate_key /path/to/privkey.pem;
        
    location / {
        proxy_pass http://personalwebsite:3000/;
    }
}